rule Payload_Exe2Hex : toolkit hardened
{
	meta:
		description = "Detects payload generated by exe2hex"
		author = "Florian Roth"
		reference = "https://github.com/g0tmi1k/exe2hex"
		date = "2016-01-15"
		score = 70

	strings:
		$a1 = {73 65 74 20 2f 70 20 22 3d 34 64 35 61}
		$a2 = {70 6f 77 65 72 73 68 65 6c 6c 20 2d 43 6f 6d 6d 61 6e 64 20 22 24 68 65 78 3d}
		$b1 = {73 65 74 2b 25 32 46 70 2b 25 32 32 25 33 44 34 64 35}
		$b2 = {70 6f 77 65 72 73 68 65 6c 6c 2b 2d 43 6f 6d 6d 61 6e 64 2b 25 32 32 25 32 34 68 65 78}
		$c1 = {65 63 68 6f 20 34 64 20 35 61 20}
		$c2 = {65 63 68 6f 20 72 20 63 78 20 3e 3e}
		$d1 = {65 63 68 6f 2b 34 64 2b 35 61 2b}
		$d2 = {65 63 68 6f 2b 72 2b 63 78 2b 25 33 45 25 33 45}

	condition:
		all of ( $a* ) or all of ( $b* ) or all of ( $c* ) or all of ( $d* )
}

