repos:
-   repo: local
    hooks:
    -   id: rulename_duplication
        name: Rule name duplication
        entry: python3 tools/ci/name_dup.py
        language: system
        always_run: true
        pass_filenames: false
    -   id: rulecontent_duplication
        name: Rule content duplication
        entry: python3 tools/ci/content_dup.py
        language: python
        additional_dependencies: 
          - plyara
        pass_filenames: false
    -   id: sevcheck
        name: Invalid score & weight
        entry: python3 tools/ci/severity.py
        language: system
        always_run: true
        pass_filenames: false
    -   id: compile
        name: Compile rules
        entry: python3 tools/ci/compile.py
        language: system
        files: .yara?
