repos:
-   repo: local
    hooks:
    -   id: dupcheck
        name: Rule duplication check
        entry: python3 tools/ci/dup.py
        language: system
        always_run: true
        pass_filenames: false
    -   id: Rule score & weight check
        name: sevcheck
        entry: python3 tools/ci/severity.py
        language: system
        always_run: true
        pass_filenames: false
